# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ada5c4edffbdf7d1ff0bda41f3f9624a175d9287a9bdcd4804d62b809698a48fd073e5f61cc280c1453f538082a2ef6458ff655caf2f58aa418544e219b4b41e

test:
  secret_key_base: 3bf5c6984ebde85dc8ded45c8f0fabb1869e3f037418209420975853690fdbda94a63fc2bc2aec6ee234e891ec656eedf6f8c17787c8c05eca62c3b596797cc6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
